version: '3.6'

services:
  app:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - '.:/app'
      - '~/.m2:/root/.m2'
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - hk-mysql
